92 fix backend linting errors
oss-slu/esp pull request #111
Opened 2024-11-18 00:04 UTC by suprajamannava17

Fixes #issue_number

**What was changed?**

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*

**Why was it changed?**

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*

**How was it changed?**

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*

**Screenshots that show the changes (if applicable):**

2024-11-19 21:03 UTC, SiriChandanaGarimella commented
@suprajamannava17 - Great work! I started reviewing the code. Meanwhile, could you please update the PR description with proper details?

2024-11-21 02:45 UTC, SiriChandanaGarimella requested changes
@suprajamannava17 - Great work! The code looks much cleaner now. Thanks for improving it. I have reviewed the code and left some comments. Can you please look into them.

2024-11-21 02:45 UTC, SiriChandanaGarimella commented on requirements.txt
Please move the requirements.txt file into the server folder.

2024-12-02 22:29 UTC, SiriChandanaGarimella commented
@suprajamannava17 - Could you please let me know once the PR is ready for review?

2025-03-07 05:36 UTC, bhumulanandinireddy commented
There are no linting errors as of now

2025-03-07 05:36 UTC, closed without merging