Fixes issue #60
oss-slu/esp pull request #68
Opened 2024-09-12 15:26 UTC by mkalal6

Fixes #60

I have created a handleDelete function; however, it does not function as it needs to. I am unsure if it is due to the new docker system since my debugging is also not printing the console logs.

2024-09-16 22:15 UTC, mkalal6 reviewed
This pull request is successful. The changes did work and I can understand what was changed through the descriptive pull request. Moving line 162 to line 18 was good to clean up the code; however, committing line 307 removal was unnecessary. Good job overall.

2024-09-16 22:15 UTC, Ebruns4 reviewed
Accurately and cleanly addresses the issue that was at hand

2024-09-19 03:01 UTC, SiriChandanaGarimella requested changes
This looks great and works fine. But, I see that there is some scope for refining the code. The searchQueryData can be removed as it adds redundant code. Please check my inline comments.

Also, can you please update the issue title to the following format: ‘Issue title (the number) fixed’? 
For example: ‘Implement the Delete functionality in the Search Query (#60) fixed’ or ‘Implemented the Delete functionality in the Search Query (#60)' is also fine.

2024-09-23 15:25 UTC, SiriChandanaGarimella approved these changes
lgtm;

2024-09-23 15:26 UTC, merged