Resolved issue #61 - Ignore the non-content elements in the search output
oss-slu/esp pull request #70
Opened 2024-09-30 16:59 UTC by Lyskawa-Aonyx

Fixes #61 - Ignore the non-content elements in the search output

**What was changed?**
I added a few lines of code in the app.py file to handle this issue
*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*
backend text processing 
**Why was it changed?**
to ensure that non-relevant chars would not be included in the output. 
*Here, describe the issue that you are fixing with this code, and why your code fixes it.*
I changed parts of the extract_sections function in app.py to handle this issue correctly and to only show relevant chars in the output preview. 
**How was it changed?**
changed lines of code
*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*

**Screenshots that show the changes (if applicable):**

2024-10-01 01:49 UTC, mkalal6 reviewed
Is there a lot of repetition of is_content_line that can be reduced? Otherwise good code.

2024-10-03 04:11 UTC, SiriChandanaGarimella reviewed
@Lyskawa-Aonyx - The changes look good, and you are in the right direction. Please check the following points:
1. Consider the search term as the title since there is no text labeled 'Title'.
2. Add a regex to ignore the header of the search term: CARTESIAN COORDINATES (A.U.)
I have added inline comments. Please check.

Also, for the next issue, please use the issue number as the branch name (e.g., issue_61).

2024-10-03 04:11 UTC, SiriChandanaGarimella commented on server/services/file_search_operations.py
>          line_empty = 0
Please add the search_term as follows:
 search_term = search_terms[0] # for now (we will need to make it generic later) 
 and pass it as the parameter value to the is_content_line() function.


Also, add the following as the header_pattern above the for-loop (line 22) and pass it as the parameter value to the is_content_line() function:
header_pattern = r'^\s*NO\s+LB\s+ZA\s+FRAG\s+MASS\s+X\s+Y\s+Z\s*$'

2024-10-03 04:16 UTC, SiriChandanaGarimella requested changes
Please check the added inline comments

2024-10-07 18:10 UTC, closed without merging